# Setup
title:        SuHome
tagline:      Suhyeon's Blog
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Suhyeon
  url:        https://github.com/bada7211/bada7211.github.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
